### ISSUE TITLE
Prohibited symbol when booting  

### ISSUE THREAD

**Issue by kefei0324** [cmer/gigabyte-z390-aorus-master-hackintosh#10]
Hi, buddy, me again.
Forgot to say that I am almost the same as your hardware.
The same motherboard, the same cpu, the same graphics card, etc.
I use your lazy configuration directly and it works perfectly.
But
I found a small problem. When starting up, occasionally a prohibition symbol appears on the screen, maybe related to the USB interface?
Whenever this happens, I can only restart it once.
Any suggestions?
Good wishes Thank you for your guide.

**Comment by vkrishnan23** [comment]
I have the same setup except for the i7-9700k. I also have the same issue sometimes where I get the prohibited symbol.

**Comment by balikci92** [comment]
I was also getting this icon, and when I restart it works. I found out the solution, you have to disable SIP, insert this in Clover > RT Variables > CSRActiveconfig > 0x67, hope it works for you.

**Comment by cmer** [comment]
I get it too occasionally. It hasn’t bothered me enough to investigate it (yet). I don’t want to disable SIP for security reasons. I will update the repo if and when I find another solution.
