### ISSUE TITLE
SecureBootModel

### ISSUE THREAD

**Issue by helix0712** [cmer/gigabyte-z390-aorus-master-hackintosh#100]
Hi,

after trying my luck on Windows, i am re-installing MacOS again :-)
I wanted to go for a fresh install, so i created my own config.plit and EFI folder from scratch...and ran into issues after the first reboot into MacOS Installer. Trying your EFI, which worked fine for me recently, i ran into the same issue.
I found the following on Reddit and wanted to leave a note as you repository was helpful to me in the past!

OpenCore gained support for signed kernel verification in a recent commit. You may get reboots in early booting due to this being enabled by default in the sample plist - make sure SecureBootModel is set to Disabled in your config.plist - and not set to Default.

After setting the Variable to Disabled, the install worked as usual.

Regards,

Patrick

**Comment by cmer** [comment]
Are you saying the OS won't install when it's enabled, but will boot just fine with it after installation?

**Comment by gajosr** [comment]
It is described in OC docs: Users may find upgrading OpenCore on an already installed system can result in early boot failures. To resolve this, see: [Stuck on OCB: LoadImage failed - Security Violation](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-ocb-loadimage-failed-security-violation) 

Easiest solution: 
copy over the Secure Boot manifests from /usr/standalone/i386 to /Volumes/Preboot/<UUID>/System/Library/CoreServices

**Comment by cmer** [comment]
I'll close this for now. Thanks for the info!
