### ISSUE TITLE
Boot picker GUI in OC 0.7.4

### ISSUE THREAD

**Issue by deariinsanity** [cmer/gigabyte-z390-aorus-master-hackintosh#102]
Hi! First of all, thanks for sharing your files. If it wasn't for you, I wouldn't be able to have a hackintosh up and running.

The thing is, after upgrading to OC 0.7.4 (again, thanks to your EFI), the beautiful GUI in the boot picker is now gone. Is there anything I can do to bring it back?

Thank you very much!

**Comment by ttran-089** [comment]
Do you have a screenshot of the "beautiful GUI"? I too would like to make a change from the defaulted UI

**Comment by deariinsanity** [comment]
The picker looked something like this:

![image](https://user-images.githubusercontent.com/76685979/136743877-cca1c0cd-0eb4-4066-b5c7-8e0be4eb49d7.png)

And then the verbose was hidden and it showed the regular Mac progress bar instead:

![image](https://user-images.githubusercontent.com/76685979/136744109-00d8ab56-7873-4d2f-8a78-43472319a46c.png)

I guess there's some kind of tweaking to be made in the config.plist file (and probably some other files need to be in the OC folder) but I want to be sure what exactly needs to be changed / included.

**Comment by HappyNacho** [comment]
You should read the Dorthania guide on how to set up OpenCanopy, this is not an issue with the repo but misconfiguration.

**Comment by deariinsanity** [comment]
I just wondered if Carl removed it because of some kind of error, but I'll look into it anyways. Thanks!

**Comment by ttran-089** [comment]
> You should read the Dorthania guide on how to set up OpenCanopy, this is not an issue with the repo but misconfiguration.

Thanks, I’ll look into this.

**Comment by ksroopraj75** [comment]
Hello Sir,thanks for sharing your files. Because of you i build Hackintosh, Otherwise  I wouldn't be able to have a hackintosh up and running. 
Normally i copy and paste your efi folder into mine and done, but this time im not able to see boot screen cant choose operating system.

**Comment by deariinsanity** [comment]
OK, so I've just fixed it. In case anyone's encountered the same issue, here's what I did:

1. [Download](https://github.com/acidanthera/OcBinaryData) the latest Resources folder and replace it in your EFI/OC folder.
2. In your config.plist, set AppleDebug to false and in boot-args remove the "-v" (this is to hide the verbose).

Closing the issue, thanks!

**Comment by ksroopraj75** [comment]
![image](https://user-images.githubusercontent.com/77128753/137230967-5c68e851-90b0-4204-b9b0-d1570e9424ca.jpg)

I did what you said but still same please help me if it’s possible 
Thanks

**Comment by Tom9876** [comment]
Hello ksroopraj75,

you also have to exchanged the value of "PickerVariant" from "Modern" to "Acidanthera\GoldenGate".
Looks like this:
```
    <key>PickerVariant</key>
    <string>Acidanthera\GoldenGate</string>
```
At least this worked for me

**Comment by ksroopraj75** [comment]
Hello Tom thanks its work for me as well.
king regards
