### ISSUE TITLE
No way to set "uia_exclude=HS14"

### ISSUE THREAD

**Issue by jbarlow83** [cmer/gigabyte-z390-aorus-master-hackintosh#15]
Clover Configuration 5.4.3.1 does not offer an option to set uia_exclude=HS14 in the Boot menu.

Right click context menu under "Boot Arguments" does not say anything about how to set this parameter.

**Comment by Oschly** [comment]
Click + button in right corner of table, then paste it. It's custom boot's argument that not many boards need. Like I have to use slide, but slide=128 which is not available from templates (only slide=0).
