### ISSUE TITLE
Clover overwrites bios settings (vCore)?

### ISSUE THREAD

**Issue by alexbohariuc** [cmer/gigabyte-z390-aorus-master-hackintosh#17]
Hey,

I’m using the same hardware, settings and EFI Folder - i noticed that my VCore values go up to 1.44v, but in bios it’s set to 1.290 at 4.9GHz. Any thoughts? Somehow Clover seems to overwrite them. @cmer are your VCore values the same as in the bios? Using HWmonitor and iStat Pro to monitor them.

**Comment by cmer** [comment]
Not sure... perhaps it's trying to use more power under load? I wouldn't worry about it if there's no issue.

**Comment by alexbohariuc** [comment]
Temps never go above 80-89 ish in full load with Cinebench. Just for the sake of it i’ll measure the VCore with a multimeter.

**Comment by cmer** [comment]
That's pretty standard for that cpu and also what I get, I believe. Let us know what your investigation reveals.

On Sat, Jun 1, 2019 at 7:24 PM, Alex Bohariuc <notifications@github.com> wrote:
Temps never go above 80-89 ish in full load with Cinebench. Just for the sake of it i’ll measure the VCore with a multimeter.
