### ISSUE TITLE
The BIOS version

### ISSUE THREAD

**Issue by Matthewmaam** [cmer/gigabyte-z390-aorus-master-hackintosh#18]
Thanks for your step by step guide. I see you currently using BIOS version F7. But gigabytes already update it to F8. Is that possible for me to follow your Hackintosh guide using the newest BIOS version?

**Comment by alexbohariuc** [comment]
I'm currently on F8 and it works fine - i only have one issue (that might not be related to the BIOS version): the VCore settings are somehow changed by OSX/Clover.

**Comment by Matthewmaam** [comment]
> I'm currently on F8 and it works fine - i only have one issue (that might not be related to the BIOS version): the VCore settings are somehow changed by OSX/Clover.

thanks, i will try it also, and give u some feedback.
