### ISSUE TITLE
Same CPU, Motherboard and  WIFI/BT adapter, but Bluetooth doesn't work well.

### ISSUE THREAD

**Issue by gaojinhsu** [cmer/gigabyte-z390-aorus-master-hackintosh#19]
![image](https://user-images.githubusercontent.com/2178687/58316711-c2a64d80-7e46-11e9-841d-db63ae075aa5.png)
![image](https://user-images.githubusercontent.com/2178687/58316432-211efc00-7e46-11e9-96c2-11521f318928.png)
![WeChat43d3c59be56691493de655f236754055](https://user-images.githubusercontent.com/2178687/58316614-8672ed00-7e46-11e9-90f4-9fb27839c2a4.png)

**Comment by gaojinhsu** [comment]
My BIOS version is F8,   if I enable the Internal Graphics,  I can't boot  macOS,  it enter a restarting loop.

**Comment by cmer** [comment]
Make sure you properly disable the onboard bluetooth/wifi.
