### ISSUE TITLE
Help Required

### ISSUE THREAD

**Issue by hamzabinamin** [cmer/gigabyte-z390-aorus-master-hackintosh#2]
I'm deciding to purchase the aorus master. I had a couple of questions I was hoping you could help me with:

1. I have an rtx 2080, I know that turing carda don't have mac drivers as of yet but I was hoping to use the iGPU on my 9700k to run macOS, would that be possible? I only plan on using the macOS for app development.

2. You also mentioned that the HDMI port on the motherboard doesn't work? Does that mean I won't be able to plugin in my monitor on that port and use macOS?

3. Do you think there would be a difference in compatibility if I buy the aorus ultra or cheaper models?

**Comment by 1alessandro1** [comment]
Hi there. Today I have just built a new hackintosh with the Gigabyte Z390 Pro and the i7 9700k. The instructions can be found here: https://github.com/cmer/gigabyte-z390-aorus-master-hackintosh/blob/master/STEP_BY_STEP.md

Luckily I had also the same GPU (RX580) which performs best according to a user needs from Mac video editing (you know the correct built in drivers for AMD graphics card make a huge difference)

Even if it's the i9 9900k just follow the instructions to build the usb installer and the post installation processing can be found here: https://youtu.be/fA9AotXqkqA

N.B do not copy from random guides, if you need to buy hardware check out what you can find on the internet first and then choose wisely.

**Comment by cmer** [comment]
iGPU doesn't work on z390 yet I believe. I'd pick up an AMD card if I were you. Makes things easier.

**Comment by cmer** [comment]
Cheaper board models should work the same.
