### ISSUE TITLE
CsrActiveConfig is wrong in Step-by-Step guide (for 10.14.5)

### ISSUE THREAD

**Issue by vadimpanin** [cmer/gigabyte-z390-aorus-master-hackintosh#20]
> Set CsrActiveConfig to 0x0 which enables SIP for extra security. This should work just fine for a Vanilla Hackintosh install and is how genuine Macs ship.

Maybe it will help someone. On 10.14.5 the value of 0x0 will lead to STOP sign on boot. 0x3e7 should be used (as it is already in config.plist). Step-by-step guide is [temporary] out of date. Same goes for PciRoot and some other.

**Comment by cmer** [comment]
Updated. Thanks for this.
