### ISSUE TITLE
Not a real issue

### ISSUE THREAD

**Issue by 20mxm** [cmer/gigabyte-z390-aorus-master-hackintosh#21]
First I would like to thank you for sharing your z390 EFI and knowledge.
I have the Gigabyte z390 Aorus Ultra. Wow it works perfectly. There's one issue I've always had but could never solve. After the Mac comes out of sleep I get a message " Disk not ejected properly"
I've tried just about every fix. Do you have a solution?

Thanks
Steve

**Comment by cmer** [comment]
Yes fix your USB with the SSDT tutorial. I believe this is what fixed it for me.

**Comment by alexbohariuc** [comment]
If the issue is with an external hdd it’s actually a problem with that specific device, not relates to Hackintosh. Check KeepDriveSpinning.
