### ISSUE TITLE
hackintosh suddenly freezes

### ISSUE THREAD

**Issue by MyGHz** [cmer/gigabyte-z390-aorus-master-hackintosh#23]
Hi, I have the same motherboard as you but using the i7 8700k, I have everything working as your build, but I have noticed that sometimes when booting the Hackintosh from a cold boot into Mojave the hackintosh freezes randomly. I does not happen while booting but after I have logged into the OS and could be surfing or just on the homescreen when it freezes, i then need to power down/restart the pc. It will do this a couple of times consecutively and then all of a sudden it's running fine and wont crush at all the entire day.

**Comment by jinxiangqiang** [comment]
Add the guide:  keepsyms=1 dart=0  slide=0 -disablegfxfirmware,  The most important thing is slide=0

**Comment by onastvar** [comment]
I have the same issue as @MyGHz, I already have keepsyms=1 dart=0 slide=0. Should this be on 1 line "slide=0 -disablegfxfirmware"? Does it fix freezing issue mentioned above?

**Comment by cmer** [comment]
try my efi. no freezing here.

**Comment by onastvar** [comment]
Thanks, already using your EFI. I have [BCM94360CD / BCM94331CD to PCI-E PCI Express x1 Adapter](https://www.amazon.com/gp/product/B076KBBFV4/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1) with MacBook Air 13 A1465 A1466 2013 2014 WiFi Bluetooth Air Port Card BCM94360CS2 AP

**Comment by alexbohariuc** [comment]
@MyGhz are you using a Sapphire Vega card? I had the same issue, and it was related to my sapphire Vega64 Nitro+. It does freeze from time to time, but so rare that i don’t even care. 

Also, you can check your OC settings - i noticed that osx handles the OC setting differently than windows.
