### ISSUE TITLE
No iGPU - i9 9900KF

### ISSUE THREAD

**Issue by LoginWong** [cmer/gigabyte-z390-aorus-master-hackintosh#25]
What should I need to change to disable the iGPU and use my Vega 64 for display output? Did I need to include NoVPAJpeg.kext in this case?

**Comment by yyjazsf** [comment]
I try, disable or no disable, all is ok, my display card also is Vega 64 . you don't need NoVPAJpeg.kext

**Comment by LoginWong** [comment]
> I try, disable or no disable, all is ok, my display card also is Vega 64 . you don't need NoVPAJpeg.kext

Thanks, by the way, I have a GTX1080 installed in my system in PCIe slot 2, And I have stuck a '2 minutes left' status during installation, should I disable it?

**Comment by yyjazsf** [comment]
> > I try, disable or no disable, all is ok, my display card also is Vega 64 . you don't need NoVPAJpeg.kext
> 
> Thanks, by the way, I have a GTX1080 installed in my system in PCIe slot 2, And I have stuck a '2 minutes left' status during installation, should I disable it?

why are you both use (amd Vega 64) and (invida gtx1080)???

**Comment by cmer** [comment]
NoVPAJpeg is now deprecated and part of WhateverGreen. To disable iGPU and get Preview/Quicklook to work, you could use this instead: `shikigva=32 shiki-id=Mac-7BA5B2D9E42DDD94` -- I'm not sure if there are any downsides however.
