### ISSUE TITLE
SuperIODevice found unsupported chip! ITE

### ISSUE THREAD

**Issue by xthaohg** [cmer/gigabyte-z390-aorus-master-hackintosh#26]
I success intall mojave by your EFI. when reboot i have it log like title. you can support me. thank you so much. this is log

![8C72E0FF-8756-4196-A7A6-14FE9D88FBD4](https://user-images.githubusercontent.com/17614727/60827511-910cfa00-a1da-11e9-9e94-9ac88a53a373.jpeg)

**Comment by cmer** [comment]
No idea, sorry...
