### ISSUE TITLE
'My EFI' Folder reflective of the step-by-step guide?

### ISSUE THREAD

**Issue by kellizer** [cmer/gigabyte-z390-aorus-master-hackintosh#27]
I'm seeing a number of inconsistencies between the 'MY EFI' folder contain in this git repo (specifically around the config.plist) 

For example - 

- **iMac18,3** is defined in the step-by-step but 19,1 is what is in the _MY EFI/config.plist_

- **shikigva=40 uia_exclude=HS14** is defined in the step-by-step however this value is not in . _MY EFI/config.plist_

The question is - which is the best approach to use? Copy the MY EFI files (after updating/generating the 3 values) or follow the step-by-step? I've have the **same hardware** as the post however neither approach has (yet) worked for me & have yet to past the install stage (this is after following the BOIS changes to the letter)?

**Comment by yyjazsf** [comment]
I use 'MY EFI' folder,
- sleep doesn't work
- shut down too slow.
- in windows10, reboot, select macos, no sound.then restart,ok
- shikigva=40 uia_exclude=HS14  I think he use dsdt instead

**Comment by cmer** [comment]
I actually try to keep it in sync, but if you see differences, a pull request would be greatly appreciated!

**Comment by cmer** [comment]
I've made a bunch of changes recently and I know that at this moment it is behind. I will update the walkthrough eventually...

**Comment by cmer** [comment]
I have completely updated the Step by Step guide and it should reflect my EFI folder now.
