### ISSUE TITLE
AptioMemoryFix.efi + EmuVariableUefi.efi

### ISSUE THREAD

**Issue by AGluk** [cmer/gigabyte-z390-aorus-master-hackintosh#28]
Dear Carl,

I've found in one thread on tonymac, for unknown reasons it doesn't accessable now, that we can use AptioMemoryFix together with EmuVariableUefi, if adding "slide=0" boot argument.
So we can use the latest AptioMemoryFix on z390 boards.

Unfortunately we still need in EmuVariableUefi, because AptioMemoryFix can't work with native NVRAM on Z390. As far as I know, the investigations are passing for now for adding Z390 native NVRAM support to AptioMemoryFix.

I think you can add this in your STEP_BY_STEP guide.

**Comment by AGluk** [comment]
I've found. That was kkho555, who point on it.

https://www.tonymacx86.com/goto/post?id=1868060

**Comment by jbarlow83** [comment]
See also here:
OsxAptioFix2Drv-free2000 has been declared toxic by its creator.

https://www.reddit.com/r/hackintosh/comments/cfjyla/i_unleashed_a_plague_upon_you_guys_and_i_am_sorry/

**Comment by jbarlow83** [comment]
Although I should add, for my Aorus Pro Wifi I have not found a bootable EFI that does not require OsxAptioFix2Drv-free2000.

It may be there is no workable solution for all z390 boards at the moment. r/hackintosh currently recommends against z390's due to the NVRAM problems.

**Comment by RamiroAlvaro** [comment]
My hardware: Gigabyte Z390 Aorus Master (bios F7), Intel i5 9600k, Sapphire Nitro+ RX580 8GB SE, Ssd Samsung 970 Evo Plus 500gb M.2 Nvme, 16gb ( 8gb X 2 ) Ddr4 3200mhz Kingston Hyperx Fury.
Works for me AptioMemoryFix.efi + EmuVariableUefi.efi + slide=0 + DISABLE IGPU, but NOT WORKING hardware acceleration in vlc or in Plex media player. 
OsxAptioFix2Drv-free2000 + ENABLE IGPU --> working hardware acceleration.
Any ideas ? Thanks.

**Comment by jbarlow83** [comment]
Based on how the conversation on that forum has developed, I tried:

AptioMemoryFix.efi + EmuVariableUefi.efi + slide=0 + DISABLE IGPU + iMacPro1,1

And that worked for me. Switching to iMacPro1,1 improves compatibility because applications will either use the dGPU or not use hardware acceleration at all. Remove any of the iGPU-related patches and disable it in the BIOS. I've only been running this for 2 days but it so far seems much more stable and sane than free2000.

That's probably the best option. Some people can get iGPU to work, however. It depends on the number of hardware devices installed, because each device makes certain demands on the memory map, and the problem we're working around is the z390 firmware does a poor job of managing the memory map.

**Comment by AGluk** [comment]
> My hardware: Gigabyte Z390 Aorus Master (bios F7), Intel i5 9600k, Sapphire Nitro+ RX580 8GB SE, Ssd Samsung 970 Evo Plus 500gb M.2 Nvme, 16gb ( 8gb X 2 ) Ddr4 3200mhz Kingston Hyperx Fury.
> Works for me AptioMemoryFix.efi + EmuVariableUefi.efi + slide=0 + DISABLE IGPU, but NOT WORKING hardware acceleration in vlc or in Plex media player.
> OsxAptioFix2Drv-free2000 + ENABLE IGPU --> working hardware acceleration.
> Any ideas ? Thanks.

Hi Ramiro.

I've similar configuration except CPU (i9-9900K) and GPU ( Vega64) in my case.
And I have working iMac19,1 in headless mode (Vega64 + iGPU for harware decoding).

Check the following:

There is a propertie "AAPL,ig-platform-id = 0300923E" for "PciRoot(0x0)/Pci(0x2,0x0)" in the Clover Configurator;

There is a patch "change GFX0 to IGPU" in the Clover Configurator;

You have Lilu and WhateverGreen kexts in you /L/E or in Other folder on EFI partition;

iGPU is enabled in BIOS (not Auto);
Dedicated memory is set to 32Mb;
Above 4G Decoding is enabled in BIOS.

**Comment by RamiroAlvaro** [comment]
> > My hardware: Gigabyte Z390 Aorus Master (bios F7), Intel i5 9600k, Sapphire Nitro+ RX580 8GB SE, Ssd Samsung 970 Evo Plus 500gb M.2 Nvme, 16gb ( 8gb X 2 ) Ddr4 3200mhz Kingston Hyperx Fury.
> > Works for me AptioMemoryFix.efi + EmuVariableUefi.efi + slide=0 + DISABLE IGPU, but NOT WORKING hardware acceleration in vlc or in Plex media player.
> > OsxAptioFix2Drv-free2000 + ENABLE IGPU --> working hardware acceleration.
> > Any ideas ? Thanks.
> 
> Hi Ramiro.
> 
> I have similar configuration except CPU (i9-9900K) and GPU (Vega64) in my case.
> And I have working iMac19,1 in headless mode (Vega64 + iGPU for hardware decoding).
> 
> Check the following:
> 
> There is a propertie "AAPL,ig-platform-id = 0300923E" for "PciRoot(0x0)/Pci(0x2,0x0)" in the Clover Configurator;
> 
> There is a patch "change GFX0 to IGPU" in the Clover Configurator;
> 
> You have Lilu and WhateverGreen kexts in you /L/E or in Other folder on EFI partition;
> 
> iGPU is enabled in BIOS (not Auto);
> Dedicated memory is set to 32Mb;
> Above 4G Decoding is enabled in BIOS.

Thanks !!!

**Comment by yyjazsf** [comment]
hey, just now. I remove OsxAptioFix2Drv-free2000, and use AptioMemoryFix-64.efi. all is ok.
what I did:
(I use cmer's  EFI folder)(Gigabyte Z390 Aorus Master )
1. use bios F8(F9 has some problems)
2. calc slide(I get 1, maybe you can skip this step,if you use Gigabyte Z390 Aorus Master )
3. unlock cfg (flow this page https://github.com/acidanthera/AptioFixPkg)
4.  in clover config( uncheck  KernelPm)

all is done

**Comment by DejanOnTheGo** [comment]
> Based on how the conversation on that forum has developed, I tried:
> 
> AptioMemoryFix.efi + EmuVariableUefi.efi + slide=0 + DISABLE IGPU + iMacPro1,1
> 
> And that worked for me. Switching to iMacPro1,1 improves compatibility because applications will either use the dGPU or not use hardware acceleration at all. Remove any of the iGPU-related patches and disable it in the BIOS. I've only been running this for 2 days but it so far seems much more stable and sane than free2000.
> 
> That's probably the best option. Some people can get iGPU to work, however. It depends on the number of hardware devices installed, because each device makes certain demands on the memory map, and the problem we're working around is the z390 firmware does a poor job of managing the memory map.

@jbarlow83 Would you please provide your EFI folder? :)
This would be amazing

**Comment by DejanOnTheGo** [comment]
@yyjazsf Ivan would you also provide your EFI folder please so we can compare what works with which config?

**Comment by DejanOnTheGo** [comment]
@cmer Do you maybe have some additional inout to the statements above? Did you maybe try any of thoose? An answear would be appriciated

**Comment by cmer** [comment]
Sorry I missed this thread. Will take a look later.

**Comment by DejanOnTheGo** [comment]
> Sorry I missed this thread. Will take a look later.

@cmer Great, I think this could be a true gamechanger for z390 boards

**Comment by DejanOnTheGo** [comment]
Okay I was able to switch to MacPro 1,1 everything works fine except Bluetooth.
For Bluetooth and WIFI i use BCM94360CS2. Wifi works.
If you want to try out here is my  EFI  you need to generate your own serial numbers etc
If you have some help regarding bluetooth let me know

[](https://drive.google.com/open?id=1KEyYrZLfN1WBXfrVJhP7FgaqStuV6tsG)

**Comment by jbarlow83** [comment]
@DejanOnTheGo You have to recompile (?) your USB-SSDT kext's if you change the platform ID. (Using USBMap.command). It may be that your USB settings are just slightly off so that the internal Bluetooth USB isn't conencted.

It's probably best to not share your serial numbers.

**Comment by DejanOnTheGo** [comment]
@jbarlow83 Can you tell me how to do that?
P.S: Serial Numbers are not inside :)

**Comment by yyjazsf** [comment]
@DejanOnTheGo  https://drive.google.com/file/d/1DOF8fmyVNs53Wo0bf5pBkDJ7KGJvz8fs/view?usp=sharing  my efi

**Comment by jbarlow83** [comment]
@yyjazsf What's your reason for unchecking KernelPm?

**Comment by DejanOnTheGo** [comment]
@yyjazsf We have very similar configs inside of the EFI - just wandering if there is any tweaking potential to eg.G. remove unrequired kexts etc.

**Comment by cmer** [comment]
I'm playing with this now. Whenever I enable my iGPU, I get the "can't boot" logo. With iGPU disabled it boots fine. Thoughts?

**Comment by jbarlow83** [comment]
@cmer If you set verbose debug messages do you get stuck at "couldn't allocate runtime area 0x....."?

The problem seems to be that the z390 firmware does a bad job of memory mapping, and if you enable the iGPU it takes up some of the memory map such that there's not enough address space left to boot (the kernel wants to be in a certain area of the address space). 

It might work to fiddle with these iGPU BIOS options:
* DVMT Pre-Allocated
* DVMT Total Gfx Mem
* Above 4G Decoding
as they change how memory is allocated, and might make enough room in the right places.

Apparently every piece of hardware you add or remove will affect the memory map, so whether it can work depends on precisely what is installed. Some people can get iGPU working (I couldn't).

It's easier to get a iMacPro1,1 without iGPU working. iMacPro assumes it does not have an iGPU and so it uses the dGPU for Quicklook, etc.

**Comment by cmer** [comment]
I'm tempted to fall back to `NoVPAJpeg` (now deprecated, but can use `shikigva=32 shiki-id=Mac-7BA5B2D9E42DDD94` with WhateverGreen)

Is there any downside doing this? I typically like to keep everything as close to vanilla as possible so I'm a bit on the fence...

**Comment by jbarlow83** [comment]
You're doing iMac19,1 + iGPU disabled + novpa? I don't know if I ever tried that combination specifically. It was enough stress for one day....

`shiki-id` looks like some kind of address or magic number that could change in the future.

This reddit user seemed to be able to get both iMac and iMacPro versions working:
https://www.reddit.com/user/skittle-brau/

**Comment by cmer** [comment]
Yeah I'm contemplating sticking with iMac19,1 because it's closer to my build (ie: same CPU & ram type)
I'll report back if I run into issues...

**Comment by RamiroAlvaro** [comment]
Works for me AptioMemoryFix.efi + EmuVariableUefi.efi + slide=0 
There is a propertie "AAPL,ig-platform-id = 0300923E" for "PciRoot(0x0)/Pci(0x2,0x0)" in the Clover Configurator;

There is a patch "change GFX0 to IGPU" in the Clover Configurator;

You have Lilu and WhateverGreen kexts in you /L/E or in Other folder on EFI partition;

iGPU is enabled in BIOS (not Auto);
Dedicated memory is set to 32Mb;
Above 4G Decoding is enabled in BIOS.

**Comment by DejanOnTheGo** [comment]
@cmer - can you try to use my EFI? For me it works great.

**Comment by cmer** [comment]
I think it's because I have so many pcie devices. I'll try though.

**Comment by cmer** [comment]
@DejanOnTheGo Your EFI doesn't work for me. I get the same error: `Couldn't allocate runtime area`. I really think it has to do with me having too many PCIe devices:

* 2x NVME
* 2x dGPU
* 1x Bluetooth/wifi
* 1x 10Gbps adapter

**Comment by DejanOnTheGo** [comment]
@cmer This could be the case 
I have internally 1dGpu 2xSSD , 1x Bluetooth Wifi , 1x HDD, 1x USB 3 4 Ports Switch.

One thing - with MacPro 1,1 I have around 10-15% more performance according to geekbench

**Comment by cmer** [comment]
Just an update on this. I've been successful and my system has been 100% stable for weeks. I will update the repo soon. Thanks all for the help.

**Comment by DejanOnTheGo** [comment]
@cmer Great then I can compare my efi with yours - I also dont have any issues for weeks :)

**Comment by DejanOnTheGo** [comment]
Update to Catalina Beta6 went smooth

**Comment by cmer** [comment]
Ok, I've uploaded my EFI. I haven't updated the step by step guide yet, though.

**Comment by erezgt** [comment]
> Ok, I've uploaded my EFI. I haven't updated the step by step guide yet, though.

i started to use your guide and then i got here...
so i'm waiting for your updated guide! thanks alot!

**Comment by DejanOnTheGo** [comment]
@cmer according to your current config plist you are still on mac 19.1 - why ?

**Comment by cmer** [comment]
`iMac19,1` is the closest thing to my build. Mac Pros don't have i9 9900k. They are Xeon-based. I always try to use the SMBIOS that is as close as possible to my build, hoping to reduce issues down the road.

I'm surprised that you're getting more performance with `MacPro1,1`. It seems like a lot. Are you able to reproduce this consistently?

**Comment by DejanOnTheGo** [comment]
@cmer yes I am :)

**Comment by jcastro** [comment]
@DejanOnTheGo would you mind sharing how you created the SSDT patches for USB using MacPro1,1? AFAIK USBInjectall won't work with that SMBIOS definition.

A bit of topic: how do you test EFI configurations? Is it fine to just use the USB Installer?. I'm asking because I want to remove the 2000 driver and change SMBIOS and if my installation becomes un-bootable it's a pain in the ass because I don't have other bootable disk (for now). So I thought I could use the USB installer to test the EFI folder first. Am I right? :D

**Comment by yyjazsf** [comment]
today, i try AptioMemoryFix.efi  + slide =1, remove free2000, it's ok,
in BIOS, switch igpu mem from 64M(default) to 32M

**Comment by cmer** [comment]
@DejanOnTheGo I was curious about the significant speed improvement you see with `imacpro1,1` so I ran my own benchmarks. Clean OSX install, same kexts. I get a much more subtle difference...

<img width="703" src="https://user-images.githubusercontent.com/412/64501951-a31a2000-d291-11e9-8c26-e703db5785ca.png">

**Comment by erezgt** [comment]
> ig-platform-id = 0300923E

can you help me? i have the same vega card cant get through boot

**Comment by yyjazsf** [comment]
@erezgt  vaga 64? try this EFI: https://drive.google.com/file/d/1DOF8fmyVNs53Wo0bf5pBkDJ7KGJvz8fs/view?usp=sharing,
BIOS setting flow cmer's setting

**Comment by erezgt** [comment]
@yyjazsf 
thanks <3
seems like it doesnt recognise the ram
i tried to replace AptioMemoryFix-64.efi with OsxAptioFix3Drv-64.efi
still get stuck in the same place 
![71105381_2448192778757960_8019690375360806912_n](https://user-images.githubusercontent.com/53472492/65138898-662df600-da14-11e9-80b2-2d1471783c31.jpg)

**Comment by alexbohariuc** [comment]
I replaced OsxAptioFix2Drv-free2000 with AptioMemoryFix.efi, currently using the EFI similar to what @cmer has.
However, i cannot boot with the iGPU enabled.

Any ideas?

I have a setup with the Aorus Master Z390, 9900k and Vega 64.

**Comment by cmer** [comment]
Same issue for me. I ended up just disabling my igpu. Lesser of two evils.

On Sat, Oct 12, 2019 at 4:56 AM, Alex Bohariuc <notifications@github.com> wrote:
I replaced OsxAptioFix2Drv-free2000 with AptioMemoryFix.efi, currently using the EFI similar to what @cmer [https://github.com/cmer] has.
However, i cannot boot with the iGPU enabled.

Any ideas?

I have a setup with the Aorus Master Z390, 9900k and Vega 64.

**Comment by alexbohariuc** [comment]
In the repo description you’re only mentioning Mojave. (I’m o Catalina right now).

**Comment by cmer** [comment]
Me too. Haven't updated the guide yet.

On Sat, Oct 12, 2019 at 7:00 AM, Alex Bohariuc <notifications@github.com> wrote:
In the repo description you’re only mentioning Mojave. (I’m o Catalina right now).

**Comment by RamiroAlvaro** [comment]
Instale Catalina en otro disco SSD, funciona correctamente con la misma EFI de Mojave.
La iGPU esta habilitada en la BIOS con la siguiente configuración:
- Dedicated memory  -> 32Mb.
- Above 4G Decoding -> enabled.

**Comment by alexbohariuc** [comment]
@RamiroAlvaro is this working for you without OsxAptioFix2Drv-free2000?

**Comment by RamiroAlvaro** [comment]
Si, estoy usando AptioMemoryFix.efi .

**Comment by tucomel** [comment]
Im using gigabyte z390 designare and got same issue from this ISSUE POST, the only solution that worked for me was MemoryAllocation.efi with 2 other .efi files, (**OcQuirks.efi** and **FwRuntimeServices.efi**)
Im attaching my EFI folder with SMBIOS info cleared, in case someone has interested for
My setup is 

- z390 designare 
- i9 9900ks
- radeon rx 5700 xt powercolor
- 32gb trident z rib
- ssd 970 evo plus
- PSU corsair hx1200 

[EFI copy.zip](https://github.com/cmer/gigabyte-z390-aorus-master-hackintosh/files/4006610/EFI.copy.zip)

**Comment by cmer** [comment]
Thanks for the info.

**Comment by acermez** [comment]
> After knowing the _2kfree_.efi ISSUE :
> Im using gigabyte z390 designare and got same issue from this ISSUE POST, the only solution that worked for me was MemoryAllocation.efi with 2 other .efi files, (**OcQuirks.efi** and **FwRuntimeServices.efi**)
> Im attaching my EFI folder with SMBIOS info cleared, in case someone has interested for
> My setup is
> 
> * z390 designare
> * i9 9900ks
> * radeon rx 5700 xt powercolor
> * 32gb trident z rib
> * ssd 970 evo plus
> * PSU corsair hx1200
> 
> [EFI copy.zip](https://github.com/cmer/gigabyte-z390-aorus-master-hackintosh/files/4006610/EFI.copy.zip)

@tucomel, You saved me from a lot of headaches, thank you!!
I have the same Mobo and CPU, I was using OcQuirks.efi and FwRuntimeServices.efi from another source, and I was experiencing a random crash on boot due to memory allocation, not sure if the "MemoryAllocation.efi" did the trick but I copied  QC+FW+MemAlloc to my clover drivers folder and it seems to be working fine now after several shutdowns and reboots. Thanks again for the help!!
