### ISSUE TITLE
OsxAptioFixDrv error

### ISSUE THREAD

**Issue by thomstark** [cmer/gigabyte-z390-aorus-master-hackintosh#29]
Running a i9 9900k on Aorus Master Z390. Followed your instructions to the t, when booting into clover and clicking on install button, got this:

OsxAptioFixDrv: Starting overrides for \System\Library\CoreServices\boot.efi
Using reloc block: yes, hibernate wake: no
OsxAptioFixDrv: AllocateRelocBlock(): can not allocate relocation block (0x19959 pages below 0x100000000): Not Found

**Comment by cmer** [comment]
See #28
