### ISSUE TITLE
Restart/Shutdown Issue

### ISSUE THREAD

**Issue by Stormtrooper67** [cmer/gigabyte-z390-aorus-master-hackintosh#3]
After selecting restart or shutdown, mojave goes through the shutdown process but the pc is still on. The monitor will show that there is no signal coming from the PC, but the PC did not turnoff. Selecting restart does the same thing. The system does not restart.

**Comment by 1alessandro1** [comment]
Hi there. Today I have just built a new hackintosh with the Gigabyte Z390 Pro and the i7 9700k. The instructions can be found here: https://github.com/cmer/gigabyte-z390-aorus-master-hackintosh/blob/master/STEP_BY_STEP.md

Luckily I had also the same GPU (RX580) which performs best according to a user needs from Mac video editing (you know the correct built in drivers for AMD graphics card make a huge difference) 

Even if it's the i9 9900k just follow the instructions to build the usb installer and the post installation processing can be found here: https://youtu.be/fA9AotXqkqA

N.B do not copy from random guides, if you need to buy hardware check out what you can find on the internet first and then choose wisely.

**Comment by cmer** [comment]
Do you have the same board? Try loading optimized settings in bios. My shutdown works 100%.

**Comment by Stormtrooper67** [comment]
Yes I have the same board. When you shutdown the computer turns off?

**Comment by cmer** [comment]
Yes it does. Make sure you read "Fixing Kernel Panics at Reboot/Shutdown" in the step by step guide.

**Comment by Stormtrooper67** [comment]
Ok, I will check on that now. Btw how about your mouse is it smooth? Mine
slows down at times. I am using a wireless mouse.

**Comment by Stormtrooper67** [comment]
I checked and I did follow everything in your guide but still when I
shutdown my computer does not turn off, its still on.

**Comment by cmer** [comment]
Can you post screenshots/video and your EFI folder?

**Comment by cmer** [comment]
My mouse is just fine as well. Everything works perfectly. If you're using a Bluetooth mouse, make sure you connected your antennas. I had weird issues with Bluetooth (Airdrop, Continuity) without the antennas attached.

**Comment by Stormtrooper67** [comment]
Something weird happened. I replaced my hackintosh drive which was installed on an intel m.2 with a samsung 970 evo m.2 just so that I have the same drives in my system and now when I shutdown my hackintosh the computer turns off.

**Comment by alexbohariuc** [comment]
So, the issue might be from the 970 Evo ssd? My Motherboard also has the leds on when i shutdown the system.
