### ISSUE TITLE
No audio on z390 master

### ISSUE THREAD

**Issue by loingh** [cmer/gigabyte-z390-aorus-master-hackintosh#30]
Everything is working. But I to am having issues with no audio, I have tried the mentioned solutions in the "audio guide?" issue raised. I have the same motherboard z390 master with the i9 9900k and using "MY EFI" by author. Any help would be truly appreciated.
Thank you!

**Comment by cmer** [comment]
I'm not sure TBH, I literally have onboard audio disabled on mine because I use an external DAC. It was working perfectly fine before, however. Perhaps the inject id has changed? Please let us know when you figure this out so I can update the guide and EFI.

**Comment by amitra1997** [comment]
FIX:

1. Remove "change HDAS to HDEF" from acpi patches
2. Add "alcid=16" to the boot arguments for layout-id injection
3. Set Inject to "No" under Audio section
4. Reboot and success!
