### ISSUE TITLE
My build just stopped after 3 months

### ISSUE THREAD

**Issue by gittyup-mac** [cmer/gigabyte-z390-aorus-master-hackintosh#34]
I am hoping you can help me with my Hackintosh build

Hardware specs are as follows
Mobo: Gigabyte Auros Master z390, BIOS F7
CPU: Intel I7, 8700k 
GPU: Sapphire Radeon Pulse RX 580 8GB GDDR5
Memory: Corsair Vengeance LPX 32GB (2x16GB) DDR4 DRAM 2666MHz (PC4-21300) 
BT/Wifi: Padarsey BCM94360CS2 WiFi Bluetooth Airport Wireless Card w/ WiFi + Bluetooth 4.0 Card to PCI-E x1 Adapter Card 

 
Corsair Vengeance LPX 32GB (2x16GB) DDR4 DRAM 2666MHz (PC4-21300) 

I used your EFI in late May except I changed config to iMac 19,2 since it uses my CPU.  (EFI Attached).

Everything worked great for the past three months (though it would tend to not wake from sleep if left for more than 24 hours).

This weekend it stopped loading.  Apple icon appears and freezes about 2/3rds of the way into loading.  When I do a verbose start it has a panic with lots of IO messages (after kexts have loaded).

When I do a safe mode boot I still get a kernel panic

I tried using the new EFI you recently posted and that doesn’t seem to load either.

Any advice would be much appreciated.

Thanks
[EFI.zip](https://github.com/cmer/gigabyte-z390-aorus-master-hackintosh/files/3527917/EFI.zip)

**Comment by cmer** [comment]
Not enough info to help...
