### ISSUE TITLE
谢谢您的efi，它很棒。但我有问题想向您请教

### ISSUE THREAD

**Issue by kang1ting** [cmer/gigabyte-z390-aorus-master-hackintosh#35]
Sleep will trigger a restart

**Comment by kang1ting** [comment]
另外，在安装后期，bios设定会组织安装程序进行。将主板设置恢复默认之后，正常。我的bios版本是F9

**Comment by kang1ting** [comment]
我的配置是
同型号主板
i9-9900kf
rx580

**Comment by yyjazsf** [comment]
power manage has some issue
