### ISSUE TITLE
No boot after latest changes

### ISSUE THREAD

**Issue by xiqs00k** [cmer/gigabyte-z390-aorus-master-hackintosh#36]
I use your EFI the "lazy way".

My hardware is very sinilar to yours. I only use  a MSI Vega VII instead of your graphics card(s).

After your latest changes (replacement of OsxAptioFix2Drv-free2000) i was no longer able to boot.

I had to change "DVMT Pre-Allocated" from 128M -> 32M in BIOS to make it work again.

I appreciate your work/ guide a lot. I'm looking forward to follow you on the way to MacOS Catalina.

**Comment by tron303** [comment]
same problem here. even with DVMT at 32M it wont start with "My EFI".  Same Board, same CPU, but Sapphire RX590 Nitro+ for gfx.

**Comment by ppogorze** [comment]
For me this build works even in MacOS Catalina.
I've updated my bios to 10d and replaced Lilu and WhateverGreen for newer versions and i've compiled new ethernet kexts (because of dropping connection when 1000mbps was set).

**Comment by cmer** [comment]
You'll need to disable your iGPU. See my updated step by step guide. I had to do the same as well.
