### ISSUE TITLE
 Hackintosh based on Gigabyte Z390 Aorus Master question on USB3

### ISSUE THREAD

**Issue by Acquario-58** [cmer/gigabyte-z390-aorus-master-hackintosh#38]
Hi, I'm new to the site and I'm new to hackintosh. Thanks for your wonderful hackintosh build,
I wanted to know if the USB mapped with your system is 5 Gbps or 10 Gbps. The motherboard has 3 USB 3.1 gen 2 or 10 Gbps. Have they even worked under hackintosh? I would also like to know if the hard disk with working Hackintosh can be cloned with, for example, Carbon Copy cloner. Thank you and forgive my English.

**Comment by cmer** [comment]
USB 3 runs at full speed. I use CCC every night for backups. Must have software!
