### ISSUE TITLE
Audio Issues with New Clover Versions and Suggested Fix

### ISSUE THREAD

**Issue by amitra1997** [cmer/gigabyte-z390-aorus-master-hackintosh#39]
Hi cmer, the audio settings on your EFI are out of date and use the deprecated layout-id injection in the audio key within devices. I have a private repository with the same mobo and overall very similar configuration and had audio stop working, and saw others having the same issue. So I fixed it in my config.plist and would like to share that info.

FIX:
1. Update AppleALC.kext
2. Remove "change HDAS to HDEF" from acpi patches
3. Add "alcid=16" to the boot arguments for layout-id injection
4. Set Inject to "No" under Audio section
5. Reboot and success!

AppleALC installation and usage guide: https://github.com/acidanthera/AppleALC/wiki/Installation-and-usage

**Comment by cmer** [comment]
Thanks for this. I completely updated my step by step guide and used this information. I don't personally use the internal audio so I didn't realize my instructions were outdated.
