### ISSUE TITLE
Plagarised Code

### ISSUE THREAD

**Issue by megatroncreative** [cmer/gigabyte-z390-aorus-master-hackintosh#4]
His script for the AppleALC was stolen from a german dev MacPeet and he is claiming it as his own.
https://www.hackintosh-forum.de/user/15790-macpeet/

**Comment by cmer** [comment]
You might want to do your homework before accusing people. 

I mentioned the source of that kext here: 
https://github.com/cmer/gigabyte-z390-aorus-master-hackintosh/blob/master/STEP_BY_STEP.md
