### ISSUE TITLE
Catalina?

### ISSUE THREAD

**Issue by TimNedvyga** [cmer/gigabyte-z390-aorus-master-hackintosh#41]
Any plans on an update to Catalina?

**Comment by yass0016** [comment]
Tried this, it didn't work on Catalina

**Comment by unitqa** [comment]
I was able to install macOS Catalina beta, but I made some modifications to the files that Carl provided. If someone is interested I can test with official version of Catalina and upload on Google Drive my EFI folder. I'm still using macOS Mojave.

**Comment by djwilmer107** [comment]
Can I get a copy of the efi you used? Thanks.

**Comment by unitqa** [comment]
Yes, sure. Give me some time just to collect and test everything with latest version of Catalina. Then I will update and upload my EFI folder.

**Comment by unitqa** [comment]
Here you go guys, I hope it helps. You can check my mini guide and also my EFI folder using this link:

https://drive.google.com/drive/folders/1y9-xHX0KbxGTyN5JSXnXx2BLn0bI6qFr

Let me know if you have problems accessing the link.

**Comment by RobertBush** [comment]
@yass0016 When you say Catalina didn't work: did you try a fresh install, or an upgrade from mojave?

**Comment by alexbohariuc** [comment]
I updated from Mojave, but i could only boot with AptioFix2Drv-Free2000 and iGPU enabled alongside the settings Carl has in this repo.

**Comment by TimNedvyga** [comment]
> I updated from Mojave, but i could only boot with AptioFix2Drv-Free2000 and iGPU enabled alongside the settings Carl has in this repo.

Same thing. Successfully updated to Catalina with this setup.

**Comment by yyjazsf** [comment]
@alexbohariuc  try set iGPU form 64M to 32M and slide=0 or 1,  or just disable igpu

**Comment by cmer** [comment]
Catalina works for me. See my EFI.

**Comment by alexbohariuc** [comment]
Suplemental update, anyone? It shouldn’t break anything, but it’s worth asking.
