### ISSUE TITLE
VCore curiosity

### ISSUE THREAD

**Issue by alexbohariuc** [cmer/gigabyte-z390-aorus-master-hackintosh#42]
@cmer if you have the time, could you install iStat Menus and check if the VCore values set in BIOS are the same? HWMonitor also shows the same values.

Mine varies from 0.9V to 1.4 (currently at 4.9GHz since I kinda lost the silicon lottery).
Temps never surpassed 85 degrees, and in Intel Power Gadget I get max 170-180W power draw, but I'm just curious if it's a reading issue, or VCore is actually messed up. 

Thanks in advance.

**Comment by cmer** [comment]
Mine is at 0.7V idling and 1.4V when running GeekBench. Seems kosher. Were you expecting something different?

**Comment by alexbohariuc** [comment]
I was actually expecting to have the same constant value as it was set in BIOS, 1.32V in my case.

Is it safe for the CPU to go beyond 1.4 sometimes or as long as these are only peaks it’s ok?

**Comment by cmer** [comment]
Totally normal. Voltage goes down when not needed to save energy and goes up under load.  Everything is working as expected. Nothing will blow up. Or at least, it shouldn't. Either way, I'm not responsible 😁
