### ISSUE TITLE
GC-Titan Ridge - Thunderbolt Settings

### ISSUE THREAD

**Issue by djwoody249** [cmer/gigabyte-z390-aorus-master-hackintosh#43]
Hi - 1st, many thanks for this - followed this and got my system up without issue and has been running great for months now.
I wanted to add thunderbolt so purchased the GC-Titan Ridge thunderbolt card. Have this installed now but can't get the TB ports to be recognised.
If I plug my phone into the port it charges but my CalDigit TB dock is not recognised at all.
Any idea on what settings or what extra kexts I need for this ?

THanks

**Comment by cmer** [comment]
You probably will need to recreate the USB map. That's my guess... https://www.youtube.com/watch?v=j3V7szXZZTc
