### ISSUE TITLE
Is it safe to upgrade to 10.15?

### ISSUE THREAD

**Issue by gaojinhsu** [cmer/gigabyte-z390-aorus-master-hackintosh#45]
Is it safe to upgrade to 10.15?

**Comment by rokmc820** [comment]
> Is it safe to upgrade to 10.15?

just turn off the built-in graphics. Otherwise, the clover bootloader panics.

**Comment by gaojinhsu** [comment]
I am so upset that I can’t access into the system, even if I turn off the built-in graphics.

**Comment by rokmc820** [comment]
> I am so upset that I can’t access into the system, even if I turn off the built-in graphics.

So did I.
I turned off the internal graphics and changed the "memory modification" driver.
Look down and see for reference.
Only the changed part is marked.

**** My EFI example ****

**Before change**
drivers
ㄴUEFI
------- EmuVariableUefi.efi
------- OsxAptioFix2Drv-free2000.efi <--------- removed

kexts
------- FakeSMC.kext <--------- removed


**After changer**
drivers
ㄴUEFI
------- AptioMemoryFix.efi <--------- changed
------- EmuVariableUefi.efi
------- VirtualSmc.efi <--------- added

kexts
------- SMCProcessor.kext <--------- added
------- SMCSuperIO.kext <--------- added
------- VirtualSMC.kext <--------- changed


If you make changes, boot and operate normally, but if you turn on the built-in graphics option, you will not be able to boot.
I think…. Maybe a memory driver (aptioMemoryFixIt is assumed that efi) causes some problems when allocating memory to internal graphics. I haven't really found a solution yet.

**Comment by gaojinhsu** [comment]
I didn’t change EFI before upgrading. And now I cannot boot, what am I going to do ? I really don’t wanna reinstall OS.

**Comment by nusserstudios** [comment]
If you have a Hackintosh, you should set an expectation that you might loose data. I'd say get a NAS, so you can back up everything before you do something like this. I'd say get an old cheap MacBook so you can pull stuff from the Apple store etc. Use Git as VCS for your EFI so you can make branches to keep track of each change. You should be able to pull an old EFI, but you'll need to go back to Mojave for sure.

**Comment by gaojinhsu** [comment]
I am fucked🤦‍♂️

**Comment by gaojinhsu** [comment]
Can you send me a copy of the changed and added kext files? @rokmc820

**Comment by rokmc820** [comment]
> Can you send me a copy of the changed and added kext files? @rokmc820

My Clover Bootloader Files.
https://drive.google.com/file/d/11sn6lAzuI9Hz2PCGs8XNfV8AQdVpV3R2/view?usp=sharing
