### ISSUE TITLE
Update to lastest BIOS - F10.

### ISSUE THREAD

**Issue by phuonghoanglua** [cmer/gigabyte-z390-aorus-master-hackintosh#47]
I just updated to bios F10 then the machine did not boot.
I found that we need to re-patch ACPI for newer BIOS.
May you try this ?

**Comment by rokmc820** [comment]
> I just updated to bios F10 then the machine did not boot.
> I found that we need to re-patch ACPI for newer BIOS.
> May you try this ?

I don't think it's a Bios problem. I boot normally.

**Comment by phuonghoanglua** [comment]
@rokmc820 Thanks. Let me try it again.
