### ISSUE TITLE
Freeze when USB drive unexpectedly ejects.

### ISSUE THREAD

**Issue by riley21** [cmer/gigabyte-z390-aorus-master-hackintosh#5]
First off, thank you so much for this build guide! It's been a huge help.  I have an older external usb 2.0 drive that will sometimes eject itself and throw up the "disk not ejected properly" notification.  This causes the computer to 'freeze', or eject all the usb devices (including my mouse/keyboard), and unplugging/replugging in the mouse doesn't fix it, only a hard restart.

Anyway to avoid the freeze?  For now I've just unplugged the drive and everything is working great.

I also read somewhere that plugging the drive into a powered usb hub will avoid the ejects, so I can try that, but it would be nice to know that in case something does eject accidentally in the future, my work won't risk being lost.

**Comment by riley21** [comment]
I added the SMCSuperIO.kext and it seems to have corrected the freeze issue.  USB drives still eject after waking from sleep but they continue working again.  

I also added the SMCProcessor.kext to help iStat display the CPU temp. 

You might want to think about adding those to your build guide, but otherwise it's worked flawlessly!  

Thanks again :)

**Comment by cmer** [comment]
See my [latest commit](https://github.com/cmer/gigabyte-z390-aorus-master-hackintosh/commit/06251ce975e41b1a7f87357136868080d8d254be). I have fixed USB 3.0 speeds and ejects.

**Comment by riley21** [comment]
Thanks! I'm on the pro wifi board so I'll have to figure out how to generate my own usb script
