### ISSUE TITLE
NoVPAJpeg.kext - still needed if you disable iGPU?

### ISSUE THREAD

**Issue by alexbohariuc** [cmer/gigabyte-z390-aorus-master-hackintosh#50]
@cmer , unfortunately, my system doesn't work with iGPU enabled. I see from your EFI that you don't have the NoVPAJpeg.kext installed, but you disabled the iGPU. Preview works fine, should i bother installing NoVPAJpeg?

Thanks!

**Comment by rokmc820** [comment]
> @cmer , unfortunately, my system doesn't work with iGPU enabled. I see from your EFI that you don't have the NoVPAJpeg.kext installed, but you disabled the iGPU. Preview works fine, should i bother installing NoVPAJpeg?
> 
> Thanks!

My system configuration is almost the same as that of the cmer.(SMBios iMac19,1)
In Catalina 10.15.1, the preview works without using NoVPAJpeg.kext without the iGPU.
If the iGPU is turn off in 10.14.x, the jpg(jpeg) file is not previewed, but in 10.1.5.1 it is previewed without no problems.

**Comment by cmer** [comment]
You guys are absolutely right. I actually forgot to add `NoVPAJpeg.kext` in my new kext folder, but it does indeed seem like it is not required for Catalina. It was definitely required on Mojave though.
I'll update the guide. Thanks for the heads up.
