### ISSUE TITLE
Does this guide apply to Z390 Aorus *Pro*?

### ISSUE THREAD

**Issue by michaeleisel** [cmer/gigabyte-z390-aorus-master-hackintosh#51]

**Comment by alexbohariuc** [comment]
It should work, but i’m not sure about the usb mapping. However, @cmer has a good tutorial this one.

**Comment by cmer** [comment]
Yes. Just different usb map like @alexbohariuc said

**Comment by gaojinhsu** [comment]
Can you send me a copy of your USBMap.kext please ? Mine is Gigabyte Z390 Aorus Pro Wifi either.

**Comment by cmer** [comment]
Different revisions of the same board can be different. You should make your own.

**Comment by gaojinhsu** [comment]
> Different revisions of the same board can be different. You should make your own.

But  you said if our motherboards are Gigabyte Z390 Aorus Master, we can use your USBMap.kext file directly, I thought it applies to  Gigabyte Z390 Aorus Pro Wifi either. I am not a lazy guy, but English is not my mother tongue. I am OK to write and read English articles(sometimes I use google translate), but not good at listening.  I  watched your video and tried my best to understand what you are saying and follow your guide, but I give up at last : ( 

I followed your Step By Step Guide on Github to install Catalina, everything is OK but bluetooth doesn't work(BCM943602CS) , I think there could be something to do with the USBMap.kext.

**Comment by cmer** [comment]
There's a chance that it might just work, but if Gigabyte releases a slightly different revision it won't. If you find a usbmap you can try it, but it might not work, or not work well.
Have you connected your bluetooth adapter to one of the internal headers? That header is likely disabled.

**Comment by gaojinhsu** [comment]
> There's a chance that it might just work, but if Gigabyte releases a slightly different revision it won't. If you find a usbmap you can try it, but it might not work, or not work well.
> Have you connected your bluetooth adapter to one of the internal headers? That header is likely disabled.
Yes，I am pretty sure I've connected my bluetooth adapter to one of the internal USB slot, actually I also tried another one , neither of them works.
