### ISSUE TITLE
Did anyone get Filevault working?

### ISSUE THREAD

**Issue by lchojnowski** [cmer/gigabyte-z390-aorus-master-hackintosh#52]

**Comment by carbonimax** [comment]
yes, with opencore

**Comment by milezzz** [comment]
> yes, with OpenCore

Oh yikes, it does not work with the Clover install method? Anyone?

**Comment by lchojnowski** [comment]
I got it working, TL:DR:

* Enable all FileVault 2 kexts
* In clover configurator -> Gui -> Unhide Preboot volume
* Once system start, select "Preboot" Volume 

Done, congrats!

**Comment by milezzz** [comment]
Oh wow thanks for the update. Hmm really torn between the two installation methods now. I know I *should* transition to OpenCore but a proper config will take days VS the ease of Clover taking a few hours.

**Comment by cmer** [comment]
When a stable OpenCore is released I'll start investigating porting my build over, but in the meantime, Clover has been reliable for me so I'm in no rush.

**Comment by milezzz** [comment]
> When a stable OpenCore is released I'll start investigating porting my build over, but in the meantime, Clover has been reliable for me so I'm in no rush.

Yeah, thanks @cmer I'm convinced. Filevault was the last must-have item I needed. Are there any other negatives to having NVRAM emulated with the z390 boards?

**Comment by carbonimax** [comment]
Last OpenCore folder for z390 Aorus Master with FileVault support.
https://dsc.cloud/2b7d02/OpenCore-0.5.3.zip

You just have to put your own platformInfo.
