### ISSUE TITLE
Z390 Elite

### ISSUE THREAD

**Issue by qbattersby** [cmer/gigabyte-z390-aorus-master-hackintosh#54]
I have followed everything to a tee. Nkow in installer and trying to format a brand new NVME drive in the slot closest to the chip when I erase it using any settings it freezes the installer at Creating Partition Map. 

Have tried from command line as well.

Booted into windows and formatted drive as exfat just to test and it works fine. 

Any ideas? So frustrating.

**Comment by cmer** [comment]
How long did you wait for the partition map to be created? It's can take some time...
