### ISSUE TITLE
Issue with bluetooth - disconnects

### ISSUE THREAD

**Issue by alexbohariuc** [cmer/gigabyte-z390-aorus-master-hackintosh#59]
Hey,

@cmer did you have any issue with bluetooth disconnecting? I have a Broadcomm, supported by default by osx, but since a few weeks ago it either doesn’t work after restart or if my PC is idle (not working on it) for a few minutes. In BIOS the peripherals are working. After a restart or two it works again. 

It happened after I updated Clover and some kexts. Do you know if there is any next that could affect it?

Thanks!

**Comment by cmer** [comment]
I never had a single Bluetooth issue on my end.
