### ISSUE TITLE
Bluetooth usb port

### ISSUE THREAD

**Issue by alexbohariuc** [cmer/gigabyte-z390-aorus-master-hackintosh#60]
In a previous issues i mentioned that bluetooth is sometimes hit or miss for me (i have the exact same card) - in bios the keyboard works (Magic Keyboard), but in OSX sometimes it fails and it needs a restart to work again.

I was curious, in what internal usb port are you connecting the Bluetooth card?

![8238CA6C-DF29-42E7-A6DF-56CBD6ED42A9](https://user-images.githubusercontent.com/2670791/76684493-1f146c80-6615-11ea-8bdf-331c76853aba.jpeg)

Thanks!

**Comment by cmer** [comment]
Onboard bluetooth is hit or miss. My bluetooth/wifi card is perfect. I honestly don't remember which port I plugged it in though. Sorry...
