### ISSUE TITLE
issue update to 10.15.4

### ISSUE THREAD

**Issue by yxb25** [cmer/gigabyte-z390-aorus-master-hackintosh#62]
Hi, do you have issues update to 10.15.4? mine says "The bless tool was unable to set the current boot disk (-69793) at the end of the update, I am having the exact same build as you.

**Comment by cmer** [comment]
I had the same issue, I just need to manually select the boot partition at bootup. Seems like the update installed fine.

**Comment by alexbohariuc** [comment]
@cmer you booted from the osx drive in clover or straight from the osx drive, skipping clover?

**Comment by cmer** [comment]
through clover

**Comment by alexbohariuc** [comment]
Mine gave the same error. I’ll try again.
