### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Blurayx** [cmer/gigabyte-z390-aorus-master-hackintosh#66]
Hi, cmer

I've been using opencore for about 3 months. I noticed in your EFI folder you use NVMeFix.kext.
personally I've never used it.

**Comment by jamesfawcett** [comment]
I think this might be to fix initialization on his backup XPG SX8200 NVMe drive.

**Comment by cmer** [comment]
Yes, using for maximum compatibility with my NVMe drives. No downside in having it either AFAIK.
