### ISSUE TITLE
Gigabyte z390 i aorus pro wifi

### ISSUE THREAD

**Issue by helix0712** [cmer/gigabyte-z390-aorus-master-hackintosh#67]
Hi Carl,

wanted to leave a "BIG THANKS". Your EFI is working for me out of the box, with no issues at all.
Motherboard: Gigabyte z390 i Aorus Pro Wifi  (so, the ITX version)
CPU: Core i3 8100
GPU: Radeon RX Vega 56 8 GB
Bluetooth: Old USB i found lying around (MacOS says Unknown Vendor :-), but the original BT Apple Keyboard works, AirPods often disconnect)
WiFi: No Wifi yet - and not needed - looking for a recommendation for USB though
I used my own USBMap.kext straight away, so not sure if yours would have even worked with my board.
Amazingly my BIOS version is F8c and during the CFG unlock procedure i had to use the same  0x5c1 value that you were using in your video tutorial.

Thanks for all the work!

Patrick

**Comment by riley21** [comment]
Also a huge thank you!! System running flawlessly on 10.14.6.   Basically just a drag and drop.  (I had built my own USBMap.kext prior and just used that).   Great youtube tutorials as well!  Really easy to follow along and get right the first time..

Mobo: Gigabyte Z390 Aorus Pro Wifi (same 0x5c1 value)
CPU: i9-9900k

I'm going to check out your overclock tutorial and see if I can make that work!

**Comment by nearlynogravitas** [comment]
Regarding CFGLock, I have a branch with the EFI tool that makes the process much simpler.

Pull request: https://github.com/cmer/gigabyte-z390-aorus-master-hackintosh/pull/71
Branch: https://github.com/nearlynogravitas/gigabyte-z390-aorus-master-hackintosh/tree/cfglock

There is also a USBMap that you can use with the Aorus Pro Wifi: https://github.com/nearlynogravitas/gigabyte-z390-aorus-master-hackintosh/tree/aorus-pro-wifi-usbmap

**Comment by cmer** [comment]
@helix0712 @riley21 You are very welcome! Glad my stuff helped!
