### ISSUE TITLE
HS06 Type 3 is USB-A; why not Type 9 or 10?

### ISSUE THREAD

**Issue by Morid1n** [cmer/gigabyte-z390-aorus-master-hackintosh#73]
Your USB.plist file sets HS06 as type 3 but according to https://github.com/corpnewt/USBMap that's a USB-A port. Why not set it to USB-C (type 9 or 10)?

**Comment by itsjavi** [comment]
@Morid1n I think you are wrong: `3: USB 3 Standard-A connector`

**Comment by cmer** [comment]
Hmmm, perhaps I made a mistake. Will check later. Thanks for letting me know.

**Comment by Morid1n** [comment]
I _think_ I might have discovered _why_ you did this, but I forget the details now. Anyway, let me know if it's correct or not. Cheers!
