### ISSUE TITLE
OpenCore 0.5.9

### ISSUE THREAD

**Issue by alexbohariuc** [cmer/gigabyte-z390-aorus-master-hackintosh#74]
@cmer Have you thought about upgrading to 0.5.9? are there any issues?
I'm thinking about upgrading today so i just wanted to check if you tried or encountered any issues.

**Comment by smokingguns** [comment]
I have updated today to 0.6.0 from 0.5.9 but was having problem with Audio port my sound works only with rear port instead of line out. Updating from 0.5.9 to 0.6.0 didn’t fix my audio port. The rest works fine.

**Comment by cmer** [comment]
I’ll upgrade soon. Haven’t had any issues whatsoever so I’ve been in no hurry!

**Comment by gajosr** [comment]
I have very similar configuration to @cmer and used his guide as an example. I'am already on OC 0.5.9 but I've made my own config.plist using OpenCore desktop guide and have some differences. 
ProtectUefiServices set to True - mention in OC guide - If on Z390, enable this quirk 
@cmer - did you intentionally set it False?
For my configuration I also changed:
XhciPortLimit = False (as I am using USB Map (@cmer thanks for your guide)
boot-args  with agdpmod=pikera as I am using RX 5700 XT
I have also OC GUI enabled with PickerMode = External
Everything works but i sometimes have kernel panic just after login with freeze. I think it may be related with updated SMCSuperIO.kext.

`panic(cpu 0 caller 0xffffff800b34153a): "thread_invoke: preemption_level 1, possible cause: blocking while holding a spinlock, or within interrupt context"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.121.2/osfmk/kern/sched_prim.c:2205
Backtrace (CPU 0), Frame : Return Address
0xffffff874baeb640 : 0xffffff800b31f5cd mach_kernel : _handle_debugger_trap + 0x49d
0xffffff874baeb690 : 0xffffff800b458b05 mach_kernel : _kdp_i386_trap + 0x155
0xffffff874baeb6d0 : 0xffffff800b44a68e mach_kernel : _kernel_trap + 0x4ee
0xffffff874baeb720 : 0xffffff800b2c5a40 mach_kernel : _return_from_trap + 0xe0
0xffffff874baeb740 : 0xffffff800b31ec97 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff874baeb840 : 0xffffff800b31f087 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff874baeb890 : 0xffffff800bac27cc mach_kernel : _panic + 0x54
0xffffff874baeb900 : 0xffffff800b34153a mach_kernel : _thread_unstop + 0x187a
0xffffff874baeb970 : 0xffffff800b33fc2f mach_kernel : _thread_block_reason + 0xaf
0xffffff874baeb9c0 : 0xffffff800b4407c0 mach_kernel : _IORWLockRead + 0x2e0
0xffffff874baeba20 : 0xffffff800b3b26fd mach_kernel : _kernel_memory_allocate + 0x2fd
0xffffff874baebaf0 : 0xffffff800b376e01 mach_kernel : _zalloc_async + 0x5f1
0xffffff874baebc20 : 0xffffff800b439aef mach_kernel : _fpnoextflt + 0x9f
0xffffff874baebc70 : 0xffffff800b2c5a40 mach_kernel : _return_from_trap + 0xe0
0xffffff874baebc90 : 0xffffff7f920dfd01 ru.joedm.SMCSuperIO : __ZN10SMCSuperIO15quickRescheduleEv + 0x3a21
0xffffff874baebd80 : 0xffffff7f920de78e ru.joedm.SMCSuperIO : __ZN10SMCSuperIO15quickRescheduleEv + 0x24ae
0xffffff874baebda0 : 0xffffff7f920dc4be ru.joedm.SMCSuperIO : __ZN10SMCSuperIO15quickRescheduleEv + 0x1de
0xffffff874baebdf0 : 0xffffff7f920dbb7f ru.joedm.SMCSuperIO : __ZN10SMCSuperIO12detectDeviceEv + 0x22f
0xffffff874baebe20 : 0xffffff800ba333e9 mach_kernel : __ZN18IOTimerEventSource15timeoutSignaledEPvS0_ + 0x89
0xffffff874baebe90 : 0xffffff800ba33309 mach_kernel : __ZN18IOTimerEventSource17timeoutAndReleaseEPvS0_ + 0x99
0xffffff874baebec0 : 0xffffff800b361565 mach_kernel : _thread_call_delayed_timer + 0xec5
0xffffff874baebf40 : 0xffffff800b361091 mach_kernel : _thread_call_delayed_timer + 0x9f1
0xffffff874baebfa0 : 0xffffff800b2c513e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         ru.joedm.SMCSuperIO(1.1.4)[3EBEC0A6-5D45-3034-A52E-8B63A6FABDA1]@0xffffff7f920da000->0xffffff7f920e9fff
            dependency: as.vit9696.Lilu(1.4.5)[E42CE60E-EC0B-33AE-A513-5383B81BF165]@0xffffff7f9208e000
            dependency: as.vit9696.VirtualSMC(1.1.4)[9DD28544-2B81-33EB-B3F1-488D0FBB0947]@0xffffff7f920b7000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[0A7D7382-66FE-391B-9F93-97A996256C25]@0xffffff7f8c445000

BSD process name corresponding to current thread: kernel_task
Boot args: keepsyms=1 debug=0x100 alcid=16 shikigva=80 agdpmod=pikera`

**Comment by itsjavi** [comment]
I am on OpenCore 0.5.9 with no issues.

Did you guys also experience low scores in the geekbench results? I don't know if I have something wrong in my EFI or Bios that makes my computer working not optimally, or these are normal results.

My hardware:

Gigabyte Z390 Aorus Master (bios F11c)
Intel i9 9900k (@ 3.6 GHz)
64GB G.Skill Trident RGB 3600MHz
AMD Radeon RX 5700 XT

CPU Bench: https://browser.geekbench.com/v5/cpu/2887910 (not even in the top 1000)
GPU bench: https://browser.geekbench.com/v5/compute/1194590

Yours are similar?

**Comment by matt-from-uk** [comment]
Hi @itsjavi 

Those scores are the same as mine with the same hardware just less RAM (32GB) and 580 GPU.
If you compare against apple benchmarks you will see that is is about the same as the iMac with 9900k so i think this is exactly where we would expect it to be and definitely not low. 

It may seem low when compared against new Xeon or Ryzen CPUs but those are using many more cores so it isn't a fair comparison.

That is my understanding anyway.

**Comment by gajosr** [comment]
Hi @itsjavi 
I have almost the same configuration and my results are very similar and I think they are ok for this configuration.
My specs: 
Gigabyte Z390 Aorus Master (bios F11c)
Intel i9 9900k (@ 3.6 GHz)
64GB HyperX Fury RGB 3200MHz
Sapphire AMD Radeon RX 5700 XT
CPU: https://browser.geekbench.com/v5/cpu/2899123
GPU: https://browser.geekbench.com/v5/compute/1198570

**Comment by itsjavi** [comment]
thank you guys! so it seems we got a pretty stable setup. congratulations.

@gajosr I also was having issues with SMCSuperIO so for now I just went back to a vanilla setup + usb mapping from this repo.

Also be careful if you have some of these settings in the config.plist:
- ProtectUefiServices=false
- RebuildAppleMemoryMap=true
- SetupVirtualMap=true
- FirmwareVolume=true

...or you disabled ethernet on your BIOS (even if you only use WiFi)...

 because my App Store stopped working and I still don't which setting caused it, so that's also why I went back to the Vanilla guide recommended settings for OC 0.5.9.

**Comment by gajosr** [comment]
@itsjavi Are you still using OC 0.5.9 and newest SMSSuperIO.kext/VirtualSMC.kext or went back to 0.5.8? I followed vanilla OC desktop guide to setup config.plist and have recommended setting for 0.5.9 but still occasionally have kernel panic during login.

**Comment by itsjavi** [comment]
I am using  OC 0.5.9 and newest SMSSuperIO.kext/VirtualSMC.kext @gajosr with no issues
but I don't have SMCSuperIO anymore

**Comment by gajosr** [comment]
Thanks @itsjavi I will also check configuration without SMSSuperIO.kext to see if I can get rid of this small issue . Did you already try updating to 10.15.6 with OC 0.5.9?

**Comment by gajosr** [comment]
So I've updated to 10.15.6 - everything seems ok. Geekbench shows quite improvement in GPU result (https://browser.geekbench.com/v5/compute/1215217). CPU result stays at the same level as on 10.15.6.
Problem with SMSSuperIO.kext still present on 10.15.6.
