### ISSUE TITLE
HDR

### ISSUE THREAD

**Issue by RamiroAlvaro** [cmer/gigabyte-z390-aorus-master-hackintosh#76]
Good afternoon, someone who got the HDR worked correctly? I have my hackintosh connected to a Sony XBR-65X905F TV by means of an HDMI 2.0b cable, the video card is an RX580 Sapphire Nitro + Special Edition. The option to enable HDR appears to me, but when enabling it the image is very bad. Thank you very much.

**Comment by bbriton** [comment]
I have HDR enabled with a Samsung tv and when in HDR mode the picture becomes very  flat and less intense.  I believe this is normal as to allow the increased dynamic range available in HDR mode.  But the picture is not pleasing so I don't use it.
