### ISSUE TITLE
Hardware acceleration

### ISSUE THREAD

**Issue by Skadi8** [cmer/gigabyte-z390-aorus-master-hackintosh#80]
Hi there
Just a head's up on a very specific issue : hardware acceleration on the 5700 XT
I have the very exact same rig as you (9900k, Aorus Master, 5700 XT) and it turns out that with your EFI / config.plist and that SMBIOS config (iMac 19,1) hardware acceleration is deactivated.
This is explicit in VideoProc, and very noticeable for instance on render times in Final Cut Pro. In order to get it working, you have to actually select an iMac Pro as your system, not an iMac 19,1. Then generate serials as usuals with GenSMBIOS and update them in the config.plist and voilà. 
Now hardware acceleration is fully supported on VideoProc and BruceX test on Final Cut Pro gains 50% speed, as with everything else graphics I suppose. 
Cheers!

**Comment by gajosr** [comment]
Hardware acceleration works perfectly fine on iMac 19,1 SMBIOS with 5700 XT when you have internal graphics enabled, you must enable it in BIOS.
Chipset → Internal Graphics : Enabled
Internal graphic works in headless mode in this configuration.

**Comment by Skadi8** [comment]
My bad if it does work in some cases then.
But internal graphics were already enabled in my case
