### ISSUE TITLE
USB keybord and mouse can't work sometime

### ISSUE THREAD

**Issue by mykright** [cmer/gigabyte-z390-aorus-master-hackintosh#82]
In fact,I have two problem with your EFI(opencore 0.6.0)

1,can't sleep,it wake up right now(or 1~2 seconds later) at the moment it fall into sleep
fixed after add 0/6D patch,but I have to wake it up by pressing the power button. sad...

- [x] 2,4k monitor miss signal and closed while start with apple logo ,everytime.
by continue press keyboard have half chance to resume.[fixed]

the dif between our hardware is :
my graphics card：sapphire rx580 4g
my wifi card:BCM943602CDP
but I don't think would cause problems above

**Comment by riley21** [comment]
I had the black screen after apple logo as well.  I fixed it by removing "agdpmod=pikera" from boot-args

**Comment by mykright** [comment]
> I had the black screen after apple logo as well. I fixed it by removing "agdpmod=pikera" from boot-args

I'll try,thank you for sharing

**Comment by mykright** [comment]
> I had the black screen after apple logo as well. I fixed it by removing "agdpmod=pikera" from boot-args

well,by  removing "agdpmod=pikera",really works.(although  black screen short time )

**Comment by mykright** [comment]
those days,I have a new problem,USB keyboard,mouse can't work even though they works well an instant before.
and I have to restart power.

**Comment by mykright** [comment]
> those days,I have a new problem,USB keyboard,mouse can't work even though they works well an instant before.
> and I have to restart power.

resolved by uninstall NTFS support software
