### ISSUE TITLE
Front USB C

### ISSUE THREAD

**Issue by pXius** [cmer/gigabyte-z390-aorus-master-hackintosh#83]
Would just like to know if there's a specific reason as to why it's disabled?

If not, how would I about enabling it?
I understand it's HS01/SS01 and I could edit the USBMap Kext, just not sure what that edit should look like.

Thank!

**Comment by cmer** [comment]
It is likely your USB map indeed. It depends which header you are using I guess...

Take a look at this: https://www.youtube.com/watch?v=j3V7szXZZTc
