### ISSUE TITLE
Message and Facetime are not working.

### ISSUE THREAD

**Issue by sebikolo** [cmer/gigabyte-z390-aorus-master-hackintosh#84]
IMessage and Facetime are not working. I have a message to contact Apple Support. How to fix it.

**Comment by gajosr** [comment]
Did you set properly Your SerialNumber, BoardSerialNumber and SmUUID? If so then maybe your Apple ID was blocked by Apple (maybe you tried to many different serial numbers in a row?).

**Comment by sebikolo** [comment]
I created a new apple ID. I generated new SerialNumber, BoardSerialNumber and SmUUID. iMessage still not working :-(.

**Comment by gajosr** [comment]
I think You should try this whole procedure: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html including Fixing en0 and ROM.
