### ISSUE TITLE
10gbe PCIe card works with your OC 0.5.8 build, not with OC 0.6.2

### ISSUE THREAD

**Issue by klebba** [cmer/gigabyte-z390-aorus-master-hackintosh#85]
Hi Carl,

Thanks for sharing this project; with very similar hardware I have been able to use it for some time without modification, which is awesome! However today I tried to upgrade to your latest revision using OpenCore 0.6.2 — everything worked out of the box again with the exception of my [Sonnet Solo10G PCIe Card](https://www.sonnettech.com/product/solo10g-pcie-card.html). The network settings panel indicated the card was now unplugged. At first I thought this could be related to the change from `IntelMausiEthernet.kext` to `IntelMausi.kext` however I was able to rule this out. Now I'm using your OpenCore 0.5.8 configuration with the kexts from your OpenCore 0.6.2 build and the PCIe card is back in function. This leads me to believe that something about OpenCore networking or PCIe changed within the last few builds, but browsing through the [changelog](https://github.com/acidanthera/OpenCorePkg/blob/master/Changelog.md) I haven't identified anything obvious.

If you have any ideas about what might have changed I would be grateful to hear them!

Thanks again,

Casey

**Comment by cmer** [comment]
Oh! Really eh! I've had so many issues with my 10Gbps card myself that I pulled it out. I never realized it was due to OC. Please keep us posted if you find out more about this.

**Comment by alkanna** [comment]
Hey, I'm successfully using an HP 10G card with SmallTree drivers here, but I had to flash the vendorID so that the driver would pick it up. I'm having sleep issues though with cmer's usbmap, so I don't know if it's related or not.
