### ISSUE TITLE
bcm94360cd  bluetooth not working

### ISSUE THREAD

**Issue by fengahan** [cmer/gigabyte-z390-aorus-master-hackintosh#87]

**Comment by gajosr** [comment]
I'am using BCM94360CD (with fenvi T919) and bluetooth works natively perfectly fine (no kexts needed).
What card are you using? Did you check your bluetooth cable connection? If so did you check that your usb ports are correctly mapped (USB Port Map - HS12/HS13 ports for internal usb should be enabled)

**Comment by fengahan** [comment]
Luckily, my network card is also FV-T919 BCM94360CD. Below is my Usb port
[![BsBJ8P.png](https://s1.ax1x.com/2020/11/03/BsBJ8P.png)](https://imgchr.com/i/BsBJ8P)

**Comment by fengahan** [comment]
My Bluetooth connection is not plugged into the motherboard. I will try again later. Thank you for your guidance

**Comment by fengahan** [comment]
Everything seems normal. My pig's head has forgotten to connect the Bluetooth connection
