### ISSUE TITLE
BIOS upgrade to F11l (not an issue)

### ISSUE THREAD

**Issue by gajosr** [cmer/gigabyte-z390-aorus-master-hackintosh#88]
Hey, just letting You know that couple of days ago I upgraded BIOS to the latest version - F11l which is available on Gigabyte site since September.
No issues so far but there are some pros like built-in BIOS CFG Lock Disable option (no need to patch firmware to support MSR E2 write). There is also option to disable Serial Port which was missing in F11c. 
I also think that booting is a little bit faster (I'm on OC v0.6.2) but this can be subjective because I didn't measure time before upgrade.

**Comment by cmer** [comment]
That's awesome thanks for letting me know!
