### ISSUE TITLE
Question: Switch from Clover to OpenCore

### ISSUE THREAD

**Issue by onastvar** [cmer/gigabyte-z390-aorus-master-hackintosh#89]
What's your best recommendation to switch from Clover to OpenCore?
Is there a step-by-step guide or similar?
Do I have to re-install OS and all the Apps?

**Comment by gajosr** [comment]
Check this: https://dortania.github.io/OpenCore-Install-Guide/clover-conversion/
No need to re-install OS.

**Comment by onastvar** [comment]
@gajosr thanks! Great news, no re-install of OS. I saw that that link. It talks about cleaning and removing clover stuff. I was going to ask if anyone had done conversion what steps (if they want to share) they took to convert Clover to OpenCore.

**Comment by onastvar** [comment]
Since I have same hardware, if I replace entire clover EFI folder with opencore EFI from @cmer (with my own MLB, Serial #, SMUUID) and if I delete Clover Junk (per https://dortania.github.io/OpenCore-Install-Guide/clover-conversion/) any other steps needed to make my system work? Has anyone done this? Thanks in advance!

**Comment by cmer** [comment]
Should work, but just put it on a usb stick and boot off that to make sure you don’t brick your system.

**Comment by onastvar** [comment]
Thank You @cmer I will try and report back.

**Comment by onastvar** [comment]
I was able to install BigSur with latest OpenCore using @cmer EFI on a spare SSD. So far everything works. Thanks!

**Comment by alexbohariuc** [comment]
> I was able to install BigSur with latest OpenCore using @cmer EFI on a spare SSD. So far everything works. Thanks!

Any issues so far?

**Comment by cmer** [comment]
I've been on Big Sur for a week without any issues whatsoever.
