### ISSUE TITLE
IGPU not appearing

### ISSUE THREAD

**Issue by mattmatt099** [cmer/gigabyte-z390-aorus-master-hackintosh#9]
Hi.
How do we know IGPU is working ? It doesn't appear in the system, all I can see is my Vega 64... Is it normal or did I miss something.
Anyway, thanks a lot for your work.

**Comment by djwoody249** [comment]
Hi - 1st many thanks for this and sharing your hard work with us. I have the exact same hardware and this repo saved me hours of frustration and pain - genius.
I also have the same issue as 'mattmatt099' above - I am unable to see my internal GPU in the system report, just my RX 580.
Can you suggest what may be incorrect or what we need to check / modify?
Thanks again

**Comment by mattmatt099** [comment]
So should it appear somewhere or is it ok ?

**Comment by djwoody249** [comment]
If you follow the link there are details on how to check. Go to the headless gpu section

**Comment by mattmatt099** [comment]
Yeah I checked but it didn't work, I tweaked a few things back in BIOS and now I can see it (with IO registry explorer) and it solved issues I had with the preview app. 
Thanks.
