### ISSUE TITLE
Internal Port type 0?

### ISSUE THREAD

**Issue by riley21** [cmer/gigabyte-z390-aorus-master-hackintosh#90]
Wondering why you mapped the internal usb2 port to 0 instead of 255? Is your bluetooth card plugged in here?  Is it more stable with type 0?

`<key>HS13</key>
					<dict>
						<key>Comment</key>
						<string>Internal &amp; Front USB 2</string>
						<key>UsbConnector</key>
						<integer>0</integer>
						<key>port</key>
						<data>
						DQAAAA==
						</data>
					</dict>`

**Comment by paulmerced** [comment]
I personally had issues where my system would wake itself due to this.
Redoing the USB Map so that the internal ports were 255 fixed it.
