### ISSUE TITLE
Thunderbolt 3 Issues

### ISSUE THREAD

**Issue by paulmerced** [cmer/gigabyte-z390-aorus-master-hackintosh#91]
Hello! Can't thank you enough for the work; I have the pretty much the same hardware as you, and my Hackintosh otherwise works great thanks to you!

I installed a Gigabyte GC-Titan Ridge Thunderbolt 3 card. Hot swap works and I'm running a second display off of an OWC Thunderbolt 3 Dock.

My problem is the System Report shows "  Thunderbolt:	No drivers are loaded." and none of the USB ports work on the dock. Do you think I need to do some kind of SSDT cleanup or USB Port Mapping?

**Comment by paulmerced** [comment]
I got the PCI device to appear in the System Report by adding SSDTs for the TB3 card, but it still says no drivers are loaded. Apparently this requires me to flash a custom firmware... wish me luck :)

**Comment by alexbohariuc** [comment]
Please keep us updated. Mine comes in a week or two.

**Comment by paulmerced** [comment]
Quick update: I followed this guide on Youtube, and now the TB3 card works perfectly!
https://www.youtube.com/watch?v=R6jrc3TxQDc
