### ISSUE TITLE
Make Wifi/Bluetooth Works.

### ISSUE THREAD

**Issue by phuonghoanglua** [cmer/gigabyte-z390-aorus-master-hackintosh#92]
I use exactly the same spec as you. 
I changed only `{{ CHANGE ME }}` variables but my wifi/bluetooth does not work.
I have wifi icon at the status bar but can not find any access point.
May I need some more step for this issue ?

**Comment by ishfanatic** [comment]
Well i was able to make native onboard wifi and bluetooth work with this EFI I added these 4 kext from open source project on intel wifi and BT


![Screen Shot 2021-01-29 at 10 54 20 PM](https://user-images.githubusercontent.com/78245586/106346428-1789a080-6285-11eb-9c05-3ba3f6b03a7d.png)

**Comment by onastvar** [comment]
@ishfanatic could you share the link(s) where you got 4 Kexts?

**Comment by onastvar** [comment]
I found 4 Kexts (links below), moved them to /OC/Kexts folder 
My native WiFi or Bluetooth still do not work

https://github.com/OpenIntelWireless/IntelBluetoothFirmware
IntelBluetoothFirmware.kext
IntelBluetoothInjector.kext

https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.2.0
AirportItlwm.kext
itlwm.kext

**Comment by eduardovaladares** [comment]
Fake.

**Comment by HappyNacho** [comment]
> Fake.

Such an impressive expression of ideas using the English language. @eduardovaladares

**Comment by alkanna** [comment]
It works with Itlwm, although performance is pretty bad (depending on what bandwidth you have available).
I get 60-80Mb/s download with it. You also have to add the kexts to your config.plist for OC to pick em up. There's not additional config, it works OOB.
DO NOT install both AirportItlwm and Itlwm, those are not compatible, it's one or the other.

**Comment by cmer** [comment]
I use a dedicated wifi+bluetooth card that is natively supported by macOS and disabled onboard.
