### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by elbobyhn** [cmer/gigabyte-z390-aorus-master-hackintosh#93]
I'm trying to enable 5.1 audio channels, but I can't get audio from built-in output.
Have you tried to configure 5.1 audio channels with your mobo?

**Comment by gajosr** [comment]
I have 5.1 speakers connected to my Aorus Master mobo and have 5.1 sound enabled. But it's only available when you create Aggregate Device under Audio MIDI Setup and choose this device as output device. 5.1 audio channels are available when I use for axample VLC and watch movie with 5.1 audio track.

![image](https://user-images.githubusercontent.com/67650429/110535456-98f40e80-8120-11eb-8512-a72a10eec10d.png)

**Comment by gajosr** [comment]
I'm using alcid=16

**Comment by alexbohariuc** [comment]
Keep in mind that 5.1 will work if there is a source that outputs 5.1 channels. I'm actually using the optical output from my Aorus Master Z390 to a Yamaha V6A receiver and it works fine, but again, if you have a 2.0 source it will output only those channels.

**Comment by elbobyhn** [comment]
![Captura de Pantalla 2021-03-12 a la(s) 21 34 39](https://user-images.githubusercontent.com/12864909/111017758-d9e75f80-837a-11eb-9c9c-3ccc885642b9.png)
I'm using alcid=16 and trying to make it work on Logitech X-530 speakers.
Still no sound coming out, am using a bluray with 5.1 audio.

**Comment by gajosr** [comment]
Did you change the output device in sound preferences to 5.1 audio? I'm using Logitech X-540 speakers and they work as intended when using VLC and video with 5.1 sound. There is no software volume control option with aggregate device so you need to control volume with volume knob.
