### ISSUE TITLE
WiFi/BT excluded but still on ?

### ISSUE THREAD

**Issue by Spagnoletto** [cmer/gigabyte-z390-aorus-master-hackintosh#94]
![Zrzut ekranu 2021-03-30 o 23 32 31](https://user-images.githubusercontent.com/81568041/113059865-3d152680-91b0-11eb-95d3-37582b472163.png)
Hey, i make my own USBMap.kext with similar to yours, but with excluded HS14 I still got Intel Bluetooth on system ? Can i make something wrong( not similar )??  Attached USBMap.kext
[USBMap.kext.zip](https://github.com/cmer/gigabyte-z390-aorus-master-hackintosh/files/6232330/USBMap.kext.zip)

**Comment by HappyNacho** [comment]
Try turning off Wifi from the BIOS settings as well.

**Comment by Spagnoletto** [comment]
> Try turning off Wifi from the BIOS settings as well.

Ok, helped. But why system still showing BT with port disabled ? If i want to use internal wifi/bt from Gigabyte on Windows, and dedicated card with bt on Mac, i need to change BIOS settings ? That's will be sad. :)

**Comment by cmer** [comment]
Not sure what you did wrong. My internal Bluetooth interface is definitely not showing here.
