### ISSUE TITLE
OC 0.6.7

### ISSUE THREAD

**Issue by alkanna** [cmer/gigabyte-z390-aorus-master-hackintosh#95]
Anyone tried updating with this config ?
I am hitting a weird error when doing so : 

OCB startimage failed : aborted

Anyone else having this issue or successfully upgraded OC ?

**Comment by gajosr** [comment]
OC 0.6.7 works perfectly fine for me with this configuration

**Comment by alkanna** [comment]
Yep, nevermind, I did it all from scratch a second time and this time I got it right :)
