### ISSUE TITLE
macOS BigSur clone SSD to NVMe/M2

### ISSUE THREAD

**Issue by onastvar** [cmer/gigabyte-z390-aorus-master-hackintosh#99]
I'm running macOS BigSur 11.4 on SAMSUNG 860 EVO SATA. I purchased Samsung SSD 970 PRO NVMe M.2 and used Carbon Copy Cloner & SuperDuper to clone SATA to M2. 

There are no errors in CLONING however, I cannot boot from Samsung SSD 970 PRO NVMe M.2, after reboot i only can see BIOS setup. I can still boot macOS BigSur from SAMSUNG 860 EVO SATA. 

Are there any other steps needed in OC to make NVMe bootable or Carbon Copy Cloner & SuperDuper are not capable of cloning bootable disks?

**Comment by ttran-089** [comment]
Check if you got the right EFI folder in the new SSD.

**Comment by onastvar** [comment]
Thanks @ttran-089. 

I checked EFI folder was missing on Samsung SSD 970 PRO NVMe M.2. I manually copied it from SAMSUNG 860 EVO SATA and now I can boot from NVMe M.2.  Thanks a lot!

I guess Carbon Copy Cloner nor SuperDuper did not copy/clone any files in EFI partition.
